name: Android CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  # Job to determine which flavors to run
  setup:
    runs-on: ubuntu-latest
    outputs:
      flavors: ${{ steps.set-flavors.outputs.flavors }}
    steps:
      - id: set-flavors
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # Run dev and prod flavors on main branch
            echo "flavors=[\"dev\", \"prod\"]" >> $GITHUB_OUTPUT
          else
            # Run only dev flavor on other branches
            echo "flavors=[\"dev\"]" >> $GITHUB_OUTPUT
          fi

  test_and_build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavor: ${{ fromJson(needs.setup.outputs.flavors) }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Lint (${{ matrix.flavor }})
      run: ./gradlew lint${{ matrix.flavor }}Debug

    - name: Run Unit Tests (${{ matrix.flavor }})
      run: ./gradlew test${{ matrix.flavor }}DebugUnitTest

    - name: Check Code Coverage (${{ matrix.flavor }})
      run: ./gradlew jacocoCoverageVerification

    - name: Run UI Tests (${{ matrix.flavor }})
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        target: google_apis
        arch: x86_64
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -memory 2048
        disable-animations: true
        script: ./gradlew connected${{ matrix.flavor }}DebugAndroidTest
      env:
        ADB_INSTALL_TIMEOUT: 10

    - name: Build APK (${{ matrix.flavor }})
      run: ./gradlew :app:assemble${{ matrix.flavor }}Release

    - name: Upload Artifacts (${{ matrix.flavor }})
      uses: actions/upload-artifact@v4
      with:
        name: app-${{ matrix.flavor }}-release
        path: app/build/outputs/apk/${{ matrix.flavor }}/release/*.apk

    - name: Upload Coverage Report (${{ matrix.flavor }})
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-${{ matrix.flavor }}
        path: build/reports/jacoco/jacocoFullReport/html/
